# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt install axel android-libbase android-libadb && axel --insecure -n 5 -o /tmp/adb_8.1.0+r23-5_amd64.deb http://ftp.us.debian.org/debian/pool/main/a/android-platform-system-core/adb_8.1.0+r23-5_amd64.deb
        sudo dpkg --install /tmp/adb_8.1.0+r23-5_amd64.deb && sudo dpkg --configure -a && sudo apt install -f
        python -m pip install --upgrade pip
        pip install pyflakes pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
    - name: Set Test Environment
      run: |
        echo "TEST_ENV=True" >> $GITHUB_ENV
    - name: Lint with pyflakes
      run: |
        pyflakes .
    - name: Set mock ADB path
      run: |
        echo "PATH=$GITHUB_WORKSPACE/tests/mocks:$PATH" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        pytest
